apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limits" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "1000m"
        memory: "1024Mi"
      min:
        cpu: "1000m" 
        memory: "1024Mi"
    -
      type: "Container"
      max:
        cpu: "1000m" 
        memory: "1024Mi" 
      min:
        cpu: "1000m" 
        memory: "1024Mi"
      default:
        cpu: "1000m" 
        memory: "1024Mi"
